### ISSUE TITLE
Can we get format specification of the train.csv and validate.csv ?

### ISSUE THREAD

**Issue by vaghelan** [Bartzi/stn-ocr#1]
I am not able to reverse engineer what is the formatting required ?

dataset_mxnet/train/1.png        1       9       10      3       4       10      4       10      10      6       6       4       140     60      140     60      36      52      123     45      144     56      0       39      0       55      48      35

Can you please send me description of it ?

**Comment by Bartzi** [comment]
Hi,

the formatting required for the label files is as follows:
You need to create a `csv` file, where `\t` is the delimiter. The first column is always the path to the image file and the other columns are the labels for that image.
I actually wrote that in the README, but I will make it easier to find ;)

Hope that helps!
