### ISSUE TITLE
purpose built svhn dataset

### ISSUE THREAD

**Issue by kineticz** [Bartzi/stn-ocr#10]
The purpose built svhn dataset link in the readme leads to:

> You will shortly be able to see all information about our new paper
> "SEE: Towards Semi-Supervised End-to-End Scene Text Recognition".

Where is the dataset itself?

**Comment by Bartzi** [comment]
I'm very sorry!

I had a wrong link in my `README.md`. But i fixed now.
Sorry for the inconvenience.
