### ISSUE TITLE
I have 3 Question

### ISSUE THREAD

**Issue by arsalan993** [Bartzi/stn-ocr#11]
Q1 : Do we need to use "eval_text_recognition_model.py" file to perform the text recognition ? 
Q2 : Can you guys provide us with a pre-trained model?
Q3 : Is this system capable to recognizing a single text in an image or a line of text containing multiple characters?

**Comment by Bartzi** [comment]
Hi,

Q1: what do you mean with use eval file? Do you mean the file `eval_text_recognition_model.py`? This file is just meant as an example on how to use the trained network in prediction mode.

Q2: You can find a pre-trained model [here](https://bartzi.de/research/stn-ocr)

Q3: The text recognition model is only able to recognize text from already cropped text lines. In our experiments on the FSNS dataset we tried to build a system that can recognize text from multiple words in an image

Hope that helps ;)
