### ISSUE TITLE
tensorflow.python.framework.errors_impl.DataLossError: truncated record at 285474855

### ISSUE THREAD

**Issue by gitUserGoodLeaner** [Bartzi/stn-ocr#13]
@Bartzi , I face a question when I run tfrecord_to_image.py:
 python tfrecord_to_image.py /home/HardDisk/research/Computer_Vision/OCR/stn-ocr/stn-ocr/datasets/fsns/fsns_data/train /home/HardDisk/research/Computer_Vision/OCR/stn-ocr/stn-ocr/datasets/fsns/fsns_data/fsns_data_train train

error information:
Traceback (most recent call last):
  File "tfrecord_to_image.py", line 39, in <module>
    for idx, string_record in enumerate(record_iterator):
  File "/home/bob/stn-ocr-py3-env/lib/python3.4/site-packages/tensorflow/python/lib/io/tf_record.py", line 77, in tf_record_iterator
    reader.GetNext(status)
  File "/usr/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/bob/stn-ocr-py3-env/lib/python3.4/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.DataLossError: truncated record at 285474855

**Comment by Bartzi** [comment]
hmm, it seems that your download failed at some point?
There cleary is an error with one of the downloaded tfrecord files...
This is all I can say right now ;)

hope it helps!

**Comment by gitUserGoodLeaner** [comment]
@Bartzi Thanks for your help,   however, I still not clear why my data will corrupted,  becuase my data downloaded by the datasets/fsns/download_fsns.py,  could your provide some advice to avoid the corruptions?

**Comment by Bartzi** [comment]
Hard to say,
did you already try to download the dataset again? Did you try to find out, which file is corrupted?

**Comment by gitUserGoodLeaner** [comment]
@Bartzi fixed the problem, thank you!
