### ISSUE TITLE
compiling on Windows

### ISSUE THREAD

**Issue by whulc** [Bartzi/stn-ocr#15]
Hi. I want to know can the code running on a Windows platform. Since it is not clearly declared that the code can't run on windows. I had tried to run the code, but the warp-ctc can't be compiled on Windows. How can I make it?

**Comment by Bartzi** [comment]
Hi,

the code should be able to run on Windows, but this is totally untested.
I can't help you if you want to run the code on Windows and I won't sugget trying to do so.

Good Luck!

**Comment by dmandreev** [comment]
Hello! I successfully compile and run stn-ocr on Windows with Cuda 8.0 & mxnet 1.0.1 , If you have questions how to do it, feel free to ask. There some tricks with warpctc and mxnet\metrics\ctc. Warpctc for Win published at https://github.com/dmandreev/warp-ctc
