### ISSUE TITLE
Cannot train on fsns data set

### ISSUE THREAD

**Issue by Jia-HongHenryLee** [Bartzi/stn-ocr#5]
Hi Bartzi:
   i try to use train_fsns.py to train on fsns data set.
   i get the following error messages:
   **if i use args, --eval-image**   
![screenshot from 2017-09-29 16-23-47](https://user-images.githubusercontent.com/18475235/31007304-b4558a96-a532-11e7-8c22-92e2da54784c.png)  
    **i don't use args, --eval-image. i just load train_file and val_file**
![screenshot from 2017-09-29 16-28-11](https://user-images.githubusercontent.com/18475235/31007442-394b2b5c-a533-11e7-9e59-e445e836f01e.png)

   my development's environment:
   ubuntu 16.04
   cuda 8.0
   cudnn 5.0
   mxnet 0.9.3

Thank you very much.

**Comment by Bartzi** [comment]
Hi,

I suspect there is something wrong with your annotation file.
The shape of the `softmax_labels` should not be `(128, 126)` but rather something like `(128, 21)` or `(128, 30)`...

The error you get when not using an explicit eval image also contributes to this objection.
Have a look at the annotation file you created, you might find the cause of the error there.

**Comment by Jia-HongHenryLee** [comment]
@Bartzi  Thank you very much. I will try it.

**Comment by Jia-HongHenryLee** [comment]
@Bartzi  Thank you very much. I execute the train_fsns.py successfully.

**Comment by ThaiLe189** [comment]
Hi @Jia-HongHenryLee 
i get the same error
how can you train_fnfs ?
thank you !

**Comment by Jia-HongHenryLee** [comment]
Hi @fly809 
  
   You can follow the suggestion of @Bartzi to check annotation file and dimension of output layer.

**Comment by ThaiLe189** [comment]
Hi @Jia-HongHenryLee 
Can you show me a example about a image and of label of it ?
Thank you!
