### ISSUE TITLE
Can it achieve multiple lines of text recognition in a image?

### ISSUE THREAD

**Issue by ponlolz** [Bartzi/stn-ocr#6]
Hey,
I have already download text_recognition_model.zip  in this [web](https://bartzi.de/research/stn-ocr#text-recognition) .

It can be successfully implemented .

But it is only to recognize a line of text in a image

Whether it has the opportunity to recognize multiple lines of text？ like this [image](https://s-media-cache-ak0.pinimg.com/originals/62/b2/61/62b2615f5de512e7d65fcc8f1f507745.png)

thanks.

**Comment by Bartzi** [comment]
Hi,

the text recognition model has not been trained to recognize text from images in multiple lines. It can only handle single lines as provided by image recognition benchmarks like the ICDAR Robust Reading Competition.

You could, however, have a look at the FSNS experiments, if you want to recognize text from multiple lines. But it won't be easy to train such a system.

Good Luck!
