### ISSUE TITLE
ctc.h no such file or directory

### ISSUE THREAD

**Issue by pribadihcr** [Bartzi/stn-ocr#7]
HIi @Bartzi,

I got the following error:
ctc_loss.cpp:509:17: fatal error: ctc.h: No such file or directory

**Comment by Bartzi** [comment]
You get the error because you did not correctly install warpctc on your system (step 4 of the installation steps) ;).
Make sure you installed it in a way, that it can be found by the compiler (try `make install`) and then it should work!
